        name: Deploy to GitHub Pages

        on:
          push:
            branches: [ main ] # Reemplaza "main" con tu rama principal

        jobs:
          build:
            runs-on: ubuntu-latest
            steps:
              - name: Checkout your repository
                uses: actions/checkout@v4
              - name: Install, build, and upload your site
                uses: withastro/action@v2